name: Generate Kanban Board

on:
  push:
    paths:
      - "tasks.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate board HTML
      run: |
        python generate_board.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site